kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3-1-partition-2vs-1pool
  namespace: f5-test003
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "one_partition_two_vs_one_pool",
        "label": "f5_test003",
        "remark": "HTTP application",
        "f5_test003": {
          "class": "Tenant"
        }
      }
    }
