kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3-1-partition-2vs-1pool
  namespace: f5-test003
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "one_partition_two_vs_one_pool",
        "label": "f5_test003",
        "remark": "HTTP application",
        "f5_test003": {
          "class": "Tenant",
          "Shared": {
            "class": "Application",
            "template": "shared",
            "app_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
          "f5_test003_1": {
            "class": "Application",
            "template": "generic",
            "app_svc_1_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.61"
              ],
              "virtualPort": 80,
              "pool": "/f5_test003/Shared/app_pool"
            }
          },
           "f5_test003_2": {
            "class": "Application",
            "template": "generic",
            "app_svc_2_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.62"
              ],
              "virtualPort": 80,
              "pool": "/f5_test003/Shared/app_pool"
            }
          }
        }
      }
    }
