kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3-partition-2-vs
  namespace: f5-test002
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "one_partition_two_vs",
        "label": "f5_test002",
        "remark": "HTTP application",
        "f5_test002": {
          "class": "Tenant"
        }
      }
    }
