apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-1
  name: app-1
  namespace: f5-test002
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-1
    spec:
      containers:
      - image: kylinsoong/backend:0.0.4
        name: backend
        ports:
        - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-2
  name: app-2
  namespace: f5-test002
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-2
    spec:
      containers:
      - image: kylinsoong/backend:0.0.4
        name: backend
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1
    cis.f5.com/as3-app: f5_test002_1
    cis.f5.com/as3-pool: app_1_svc_pool
    cis.f5.com/as3-tenant: f5_test002
  name: app-1-svc
  namespace: f5-test002
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    cis.f5.com/as3-app: f5_test002_2
    cis.f5.com/as3-pool: app_2_svc_pool
    cis.f5.com/as3-tenant: f5_test002
  name: app-2-svc
  namespace: f5-test002
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-2
  sessionAffinity: None
  type: ClusterIP
