kind: ConfigMap
apiVersion: v1
metadata:
  name: cis-test-configmap
  namespace: f5-test-001
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.18.0",
        "id": "cis-test-configmap",
        "label": "f5_test_001",
        "remark": "HTTP application",
        "f5_test_001": {
          "class": "Tenant",
          "f5_test_001_4": {
            "class": "Application",
            "template": "generic",
            "app_1_svc_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.71"
              ],
              "virtualPort": 80,
              "pool": "f5_test_001_app_4_svc_pool"
            },
            "f5_test_001_app_4_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
           "f5_test_001_5": {
            "class": "Application",
            "template": "generic",
            "app_2_svc_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.72"
              ],
              "virtualPort": 80,
              "pool": "f5_test_001_app_5_svc_pool"
            },
            "f5_test_001_app_5_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
